# Generated by Django 5.2 on 2025-06-14 17:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion_type', models.CharField(choices=[('jpg_to_pdf', 'JPG to PDF'), ('png_to_pdf', 'PNG to PDF'), ('pdf_to_jpg', 'PDF to JPG'), ('resize_image', 'Resize Image'), ('compress_image', 'Compress Image')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('converted_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='converter_c_status_a20d27_idx'), models.Index(fields=['created_at'], name='converter_c_created_d889bc_idx')],
            },
        ),
    ]
